### ISSUE TITLE
Easter Egg Request : Atari ST music

### ISSUE THREAD

**Issue by a1exh** [Pyrdacor/Ambermoon.net#110]
The writers of Ambermoon (and it's prequal Amberstar) Thalion were historically legendary Atari ST demo programmers and typically they wrote their games for the Atari ST and ported them to the Amiga. When Ambermoon was first planned it was to be for the Atari ST, Commodore Amiga and IBM PC just like Amberstar. However things were not to be, only the German Amiga version was published.

But the music for the Atari ST version was commissioned and completed, arranged by Gunnar Gaubatz aka BigAlec who had previously re-arranged Amiga music from composer Matthias Steinwachs for an earlier Thalion game "No Second Prize". The data files re-surfaced in 2005 and were turned into an Atari ST demo 

https://www.youtube.com/watch?v=f2AUV3FDgrY

I would like to request the option to play the Atari ST versions of the music. (Simple eh?)

Their native format is called Triplex, an Atari ST tracker written by BigAlec, don't worry I understand it would take too long to reverse engineer another tracker and sound chip so Grazey of PHF has converted them to SNDH. This is widely supported format which is a combination of "tracker data + 680x0 based player" but SNDH players require 68000 emulators so Leonard of Oxygene is converting them into YM format. YM format is a synced stream of YM2149 register writes. YM format is the most basic Atari ST music data format which can "easily" be turned into stereo WAV using Leonard's open-source YM2149 stream player called StSound https://github.com/arnaud-carre/StSound

I know this is a big ask for such a little feature but I still think it would be cool for fans to be able to switch between Amiga and Atari ST music and dream the game had once been available for the Atari ST.

Let me know if this could be done and I will provide the YM data files.

**Comment by Wickez** [comment]
I wish to offer my highly uneducated opinion.

The general idea of implementing the "lost and now restored" music is great. But the timing is not right, since the initial full release of Ambermoon remake should have other priorities than another fan request.

Plus, any Thalion Software content is extremely rare and utilizing this one as an Easter Egg would feel rather reckless. Instead, I would leave it for the sequel Pyrdacor planned. Yes, far into future, but better good things take time.

**Comment by a1exh** [comment]
It isn't new content. It is the Ambermoon music in Atari ST format. The music sounds almost the same but obvious to anyone who ever had an Atari ST.

Yes you're right the timing is wrong. This is perhaps a feature for 1.1

**Comment by kovacm** [comment]
AlexH - idea is FANTASTIC! I obviously prefer ST YM sound since I grow up with ST. BigAlec did great job with conversion! I hope Pyrdacor will find time in future to implement this idea... in meantime I play Ambermoon net while listening YouTube music of BigAlec ;)

**Comment by Pyrdacor** [comment]
The music sound pretty cool. I will have a look at this now. Can you provide the data files for testing? You can also send them per mail.

**Comment by Pyrdacor** [comment]
I will extend the idea of a secondary set of music and provide a general music interface so that you can use the Amiga music, Atari music and even the new versions of Matthias as mp3 etc. 

Perhaps I will develop this in stages so that the Atari music is available faster but the goal is to allow multiple music inputs.

**Comment by a1exh** [comment]
I am waiting for @arnaud-carre to get back to me on how to convert the SNDH files into STSound files.
