### ISSUE TITLE
A fully charged magical lantern has no charges left after selling and buying it from the merchant

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#121]
Sell the lantern, buy it back and try to use it:

![40](https://user-images.githubusercontent.com/5891591/126996113-1c918d8e-0108-4ab3-b463-6cfb862bcf7e.png)

Working on WinUAE.

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6878517/Saves.zip)

edit: I also tried a Firebrand sword with the same result, so it seems all items are affected.

**Comment by Pyrdacor** [comment]
I wonder how the original handled this. The merchant can stack all kind of items, even magic ones. When I stack lanterns with different amounts of charges how can those charges be determined afterwards because the number of remaining charges is stored per item slot and not per item. Or to be more precisely an item slot only stores the item index, the amount and the number of charges.

Can someone test how this works in the original? For example sell two lanterns with different number of charges, buy both back. What number of charges do both have then?

I will then adjust my code to reflect the original behavior.

**Comment by Uukrull** [comment]
> Can someone test how this works in the original? For example sell two lanterns with different number of charges, buy both back. What number of charges do both have then?

![41](https://user-images.githubusercontent.com/5891591/127136976-90e66041-713f-41bb-b498-fb70b57563eb.png)

The first one is empty and the second one fully charged (5). With the Amiga version, if I sell the empty one and then the full one and buy them back, both are empty. If I sell the full first, both are full.

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6884611/Saves.zip)


And another minor bug: if I try to sell an item with the game windowed and then switch to fullscreen with the F11 key, the area where the cursor can move isn't updated. More or less the red rectangle:

![image](https://user-images.githubusercontent.com/5891591/127136514-fb837b13-13dc-499f-a6d2-9e98bfef01a2.png)

**Comment by Pyrdacor** [comment]
This should be fixed in 0.9.5 now. I decided to add another RC version before 1.0 so everyone can related to a fixed 'stable' version. It got a bit confusing which bug was found in which state of the test release so this will hopefully make it a bit easier. Moreover I watched a Let's Play of the remake and those guys were a bit confused with the controls. People who don't know Ambermoon seem to play it as well. And I added a bit stuff to make it easier for new players. So I released another pre-1.0 release so they can test the game better without knowing it.

**Comment by Pyrdacor** [comment]
I will have a look at the fullscreen issue soon.

**Comment by Uukrull** [comment]
> This should be fixed in 0.9.5 now.

Yep. I tested all possible combinations and also items with infinite charges and works like in the Amiga version. Many thanks!

**Comment by Pyrdacor** [comment]
@Uukrull Can you compile and test the "mouse trap area" when switching fullscreen?

**Comment by Pyrdacor** [comment]
If it works you can close this.

**Comment by Uukrull** [comment]
Working perfectly. Many thanks!
