### ISSUE TITLE
Issue after using a vial of strength (brown/green)

### ISSUE THREAD

**Issue by skdubg** [Pyrdacor/Ambermoon.net#145]
hello,

many hours far away i used a vial of strength (brown/green).
after that the weight of the member decreased to 0.

currently I do not have a savegame with a vial of strength to verify this again. But it happened at least twice. 
Can anyone check this with own savegame?

greetings

**Comment by Pyrdacor** [comment]
Hi nice catch! I fixed it in the most recent commit.

You mean the Revitalizing Flask which cures the exhaustion condition. The problem was that it always reverted the effect even if you wasn't exhausted.

Exhaustion halves the attributes and stores the previous values in some temp location in the character data. When reverting it takes the temp values and set it back as the current values. Of course if you are not exhausted the temp values are all zero. So in that case all the attributes are set to 0. Except for some equipment bonus etc.

**Comment by skdubg** [comment]
Thanks for the fix and the explanation. I did not know that yet. :)

tested in latest Test-Release

**Comment by Pyrdacor** [comment]
You should also know that the potion and spell (healer can also cast it) is useless. It removes the condition but as you still haven't slept for more than 36 hours, when the next 5 minutes are reached (or next hour, don't remember exactly), the condition is applied again. Only sleeping will help. It may only help to move a few steps and as mostly the whole party is exhausted, you need 6 potions for a few steps.
