### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by Pyrdacor** [Pyrdacor/Ambermoon.net#18]
I will prioritize the next steps here so you can see what's coming next and what I am working on. This should also allow others to pick stuff for contribution.

**Next steps**
- Add game data writers #53 
- Add place data reader
- Add battles (event, window, monster groups, images, etc) #43 
- Add skies and day-night-cycle #44 
- Add music. #30 

**Ideas for contribution**
- Test performance of larger render texts and if the performance is bad, find reasons for it.
- General performance tests / fps in 2D maps, different sized 3D maps, look angles, UI windows etc.
- Tests if features work as expected. Explore maps, open chests, load different save games, etc.

More to come. I am open for suggestions. I will update this list from time to time. Stay tuned. :)

**Comment by Thallyrion** [comment]
Load Savegame Option would be nice. It would make testing different saves easier.

**Comment by Pyrdacor** [comment]
@Thallyrion This is a really good idea. I will add it alongside the buttons. The portrait stuff is almost done already. But will only have time tomorrow or on monday for it.

**Comment by Metibor** [comment]
Great to see, what's coming next!

Because of the topic 'audio' is not on the list yet, I did a little bit of research regarding that:
AFAIK there games has no sound effects at all, just the music.
The original uses the SonicArranger music format.
There does not seem to exist a player for that format on the PC that is not using some kind of Amiga emulation.

Are you planing to implement a player in C# for the original modules?
If so, [this site](http://wt.exotica.org.uk/players.html) could be helpful:
It contains an archive with the 68k Assembler source code from the SonicArranger EaglePlayer-Plugin by Wanted Team which itself uses the code from the original Sonic Arranger 2.18.

I myself don't speak Assembler.
So I downloaded the Soundrack as MP3 from the [Matthias Steinwachs fan page](http://www.nemmelheim.de/steinwachs/downloads.php) and implemented a little prototype using [NAudio](https://github.com/naudio/NAudio).

The only feature for now is, that it is able to play the correct music on map changes.
=> In the original, the Lyramion world map plays music 14 (Plodding along), but I cannot find the association. The data files for the world map contains 0

mapID:musicID:mapName
255:0:Lyramion255
256:0:Lyramion256
257:25:THALION BÜRO
258:31:GROSSVATERS HAUS
259:18:GROSSVATERS KELLER
260:18:ALTE HÖHLE - 1.EBENE
261:18:ALTE HÖHLE - 2.EBENE
262:14:GEHEIMZIMMER
263:5:DIE STADT SPANNENBERG

The engine would be able to play sound effects, if someone wanted it.

...And now just saw, that you use BASS in freeserf.net
...which leads my research to this: https://support.xmplay.com/files_view.php?file_id=499
Is it possible to use XMPlay plugins in BASS as BASS uses the XMPlay engine?

**Comment by Pyrdacor** [comment]
Yeah the plan was to code a player in C#. If Bass is able to do so this would be great. I am not that familiar with Bass and plugins. I learned enough to make it work in freeserf.net and it wasn't that easy. So I can not help with additional info on the xmplay plug-in front.

I understand a bit assembler but I don't know if it will be enough to decode the player. And it will cost a lot of time which I won't have at the moment.

Using MP3 is fine but I would love to support playing the data from the original files. The sound might also be much better.

The music index 0 means "play the default music" or "keep music playing on map enter". At least I think so. I guess there is no real music id so that moving from one world map to another would not start the music from the beginning every time. There are also map events for music which also use index 0 for "back to default musicol of the map".

**Comment by Metibor** [comment]
Okay, I am listening to the extracted files from Music.amb just now.
They are playing fine inside XMPlay with the xmp-delix plugin.
In theory it can be done, but xmp-delix is a Windows 32-bit dll and that would be a very limiting factor.
Also the original [web page](http://web.archive.org/web/20171029074618/https://ssz.bitbucket.io/input_plugins.html#delix) of the plugin has vanished.

So I don't think, that we should take the approach with the plugin.

In the next days I will make a branch with the quick & dirty mp3 solution and put it in my repository.
Maybe we can use it temporarily or as a second option later if someone has done a remaster of the soundtrack. :-)

**Comment by Pyrdacor** [comment]
I would suggest an interface for both player and track/music in the Ambermoon.Data.Common assembly so we can exchange them easily later. Maybe you could add a new project called Ambermoon.Audio.MP3 or something similar which implements the interfaces and is used in Ambermoon.net project.

**Comment by Pyrdacor** [comment]
Things to come are now tracked in #63
