### ISSUE TITLE
Walking through the mine door after having it opened doesn't teleport inside the mine

### ISSUE THREAD

**Issue by Talmit** [Pyrdacor/Ambermoon.net#189]
On Kire's moon in Kiredon, when walking through the mine door after having it opened with the key, no teleport into the mine map occurs:

![image](https://user-images.githubusercontent.com/88923192/131648778-dbdc1557-fd49-4f74-b2d1-94a3a0b34a14.png)

![image](https://user-images.githubusercontent.com/88923192/131648809-8a1f9be3-ff3b-4c21-9854-4f52b41e6f50.png)

When continuing to walk, the game crashes after leaving the map.

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/7089995/Saves.zip)
Ambermoon 1.0.0, 27.08, relevant Save is Siran2

**Comment by Pyrdacor** [comment]
Ok this will be fixed in 1.1. Unfortunately your save will still be broken. So I fixed it manually. I guess the savegame should already work with the current 1.0 release.

[Save.07.zip](https://github.com/Pyrdacor/Ambermoon.net/files/7090621/Save.07.zip)

**Comment by Pyrdacor** [comment]
Moreover the mine door should be locked everytime you approach it from outside. This is also the reason why you keep the mine key. This will also be fixed in 1.1 but your savegame will not be fixed. But you still can enter the mine without having to unlock the door with the fixed savegame above.

Thanks again for your bug reports. But I have one wish. Could you zip/send only the save slot which is affected? For example only the Save.07 folder? Because I don't want to replace my whole save folder and just copy your save slot into one dedicated save slot on my local game. So I always have to find out which slot is for example "Siran2". ;)

**Comment by Talmit** [comment]
Thanks, I'll see that I'll only include the Save.xx folder. Fortunately I already passed the entire mine before I noticed the issue - I thought that this door required the key every time, so I wanted to check for my other post when I noticed the error. I could continue to morag in the meantime - I guess I'll soon be finished with this playthrough :) Thanks once more for all the great work. I really did enjoy replaying ambermoon and it does run fantastically smooth in ambermoon.net which is a real blessing.
