### ISSUE TITLE
Graphical glitch from Amiga

### ISSUE THREAD

**Issue by skdubg** [Pyrdacor/Ambermoon.net#199]
hi,

it's possible to fix this graphical issue on the map from Barons palace?
its occurs on Amiga files too.

![Unbenannt](https://user-images.githubusercontent.com/8874416/132295246-691879ed-a2c6-43c4-8445-e24861a1ac36.jpg)

**Comment by Pyrdacor** [comment]
The funny thing about this is that I had to work hard to achieve this same behavior in the remake. It may look odd on this map but is helpful for the crystal wall in the temple of brotherhood. Maybe this is just a bug in the Amiga version but I came up with a solution to let the remake look exactly like it.

This behavior is controlled by a wall flag which I interpreted as "block sight". Which basically is used for all kind of walls and is not used for things like spider webs, door arcs, etc.

The logic is like this:
1. If a tile does not block sight and not block movement -> show not at all on the map
2. If a tile does not block and also blocks sight -> fake wall / secret door
3. If a tile does block and also blocks sight ->wall
4. If a tile does block and does not block sight -> also a wall

Case 1 is easy. Case 2 will appear as a normal wall if you have not activated Mystic Map or Find Secret Doors.

Case 3 and 4 describes the behavior above. They are both drawn as normal walls in any case. But when they are next to each other, they are not visually connected. This happens here.

As I said before it is a helping indicator for the crystal wall in the temple of brotherhood. I think the crystal wall has the flag "blocks sight" set to false in contrast to the other walls.

But here in the palace those walls should have the flag set. Up to this day I am still not 100% sure if my interpretation of the flag is correct. So that it indeed means "block sight". But it fits more so many tiles.

I will try to set the flag for those two wall pieces and check what happens in the Amiga version.

**Comment by skdubg** [comment]
at first I thought there was something to do on this wall (but there is only a picture with the sailboat you got).
but you can obviously do nothing here.

Very interesting your information. thanks

**Comment by Pyrdacor** [comment]
This is now fixed in the original data. It will be part of the next original game data updates which hopefully are released tomorrow.

@a1exh In case you are interested how it was fixed. Change byte 0x0AA1 in sub-file 005 of 2Lab_data from 0x80 to 0x82. This will set the "Block Sight" flag like all the other walls have.

Since original german v1.1, the files 2Lab_data.amb and 3Lab_data.amb are exactly the same. For consistency the same change should also be applied to 3Lab_data.amb. But you can also just copy 2Lab_data.amb and rename it to 3Lab_data.amb. In general only 2Lab_data.amb should be used for the maps that matter. In this case I guess this particular map is the only one who uses this wall as it has the little picture with the boat on it.

**Comment by a1exh** [comment]
@Pyrdacor this is probably unrelated but two other map draw issues were reported by Meynaf as Unfixed Bug 15?

> @Meynaf : [If you re-explore the space ship after having moved with it (to a moon), corruption appears in the left part of the automapper](http://eab.abime.net/showpost.php?p=370772&postcount=17)
> @dlfrsilver : [Corrected with data file from the German version](http://eab.abime.net/showpost.php?p=1072905&postcount=69)

I was never able to substantiate the fix (due to lack of details) hence why it is on the unfixed sheet.

**Comment by Pyrdacor** [comment]
The "moved space ship" are different maps. There are 3 map version (1 map for each world). So according to meynaf this would mean that the versions on the moon are corrupted. I will have a look.

**Comment by Pyrdacor** [comment]
Hm I don't see any issues even with the english 1.07 from your site. Is that the original or a fixed version?

The only thing I noticed is, that there are blocks/tiles which use wall indices which are not part of the labdata. The remake even crashed when casting "Map View". Those walls are outside the visible range.

**Comment by a1exh** [comment]
That is the original version.

**Comment by skdubg** [comment]
hi,
there should be the same glitch at the beasts cave:

![Unbenannt](https://user-images.githubusercontent.com/8874416/135712297-6147ea99-363e-48df-88ee-93dae1f19d14.jpg)

**Comment by dlfrsilver** [comment]
What is the glitch for the beast cave?

**Comment by Pyrdacor** [comment]
See the parts below the player in the screenshot.

**Comment by Pyrdacor** [comment]
This is fixed by: change byte 0x0641 in sub-file 026 (dec) in 2Lab_data from 0x80 to 0x82.

**Comment by Pyrdacor** [comment]
This fixes all issues in the hill caves and the beast cave as well.

**Comment by Pyrdacor** [comment]
Is fixed in 1.3 remake. But I have to release original versions in the next days to make it available on Amiga as well.
