### ISSUE TITLE
Where is the Intro?

### ISSUE THREAD

**Issue by haja00011** [Pyrdacor/Ambermoon.net#234]
Hi,

First of all, exciting project. To be honest I never played it until the end. Maybe I can change it now :)

If I start the program I don't see the intro. 
I don't know if it is a bug, not implemented or if I simply don't see it ;-)

1. I see the _Pyrdacor_ Logo
2. I see: _Wähle eine Spieldaten-Version_ (I can choose _1.11 DEUTSCH_, _1.12 ENGLISH_)
3. If I choose: _1. 1.11 DEUTSCH_: I see the Thalion Logo
4. After that I see menu _NEUE QUEST STARTEN_, _QUIT_
5. After pressing _NEUE QUEST STARTEN_ I can choose my character
6. After I chose my character I am directly in the house of the grandfather
7. If I choose the _English_ version it is exactly the same.

Version: 1.3.0 for Windows 64bit
My OS: Windows 10, Version 21H1 (Build 19043.1288)

Best Regards 
Jan

**Comment by Pyrdacor** [comment]
Hi Jan. Thanks for your feedback. The intro is not implemented. To be honest the reason is priority, time and difficulty.

The intro is a program in its own. This is also true for the outro but the outro was rather easy to decode. At least it only consists of moving text and changing images. But the intro has flying meteors, fleeing little people and a lot of other stuff. Decoding it might take weeks. So to release the remake in a reasonable amount of time after all feature were implemented, I decided to skip the intro.

I might add it at a later point in time.

**Comment by haja00011** [comment]
Hi Pyrdacor,

thank you for the answer.

Best Regards
Jan

**Comment by Pyrdacor** [comment]
I'll create a feature request for the intro so it won't be forgotten. When I have time for it, I'll try to add it. ;)

**Comment by Pyrdacor** [comment]
See here: #235

**Comment by Pa9an** [comment]
Just a thought...until the "real" intro is done, why not just add a VIDEO version of the intro?
Basically stream the Amiga intro to a flv or so and play this ahead of the game?
That'll buy you some time...and probably noone would even question it... :)

**Comment by Pyrdacor** [comment]
This idea was already suggested by others but trust me it still isn't that easy. Integrate a video playback into the current engine will take days if not weeks of work too. Not to mention a video playback that is resolution independent and still looks good.

**Comment by Pa9an** [comment]
Oh, sorry, I wasn't aware of that. Ignore what I said then...I'll keep checking YT for the intro when I feel like it and wait for your proper implementation ;)
