### ISSUE TITLE
deactivate noclip function?

### ISSUE THREAD

**Issue by invisiblehsadow** [Pyrdacor/Ambermoon.net#260]
the noclip function is wonderful !, it would be nice if you could switch off the noclip function again in the game, if you key it in again it remains active, so you have to close ambermoon.net again and again and reload it 

die noclip funktion ist wundervoll!, wäre schön wenn man die noclip funktion aber auch wieder im spiel abschalten könnte, wenn man es noch mal eintippt bleibt es aktiv, so muss man immer wieder ambermoon.net beenden und neu einladen

**Comment by Pyrdacor** [comment]
You can do so already.

`noclip 0`

Those commands (godmode is another example) have an optional argument which is 0 for off and 1 for on. The default is just 1 so that it is turned on when you omit the argument like in `noclip`. It is equivalent to `noclip 1`.

You can see this in the help of the command: `help noclip`

**Comment by Pyrdacor** [comment]
But I guess when using it without argument it should toggle the mode instead. Therefore I created a new feature request here: #281
