### ISSUE TITLE
[Bug report] gadlons cellar 1

### ISSUE THREAD

**Issue by invisiblehsadow** [Pyrdacor/Ambermoon.net#279]
in the gadlons cellar 1, the monsters were outside the walls and i couldn't fight them
![00](https://user-images.githubusercontent.com/95400798/144482687-e3e9d867-0fe8-4d1f-a0f6-ac449d5f5795.png)

**Comment by Pyrdacor** [comment]
This is a bug in the original data. There are no monsters in the original as well. The difference is that you can't see the monsters on the map in the original. But actually there are 8 monsters on the map. But they all have their spawn location at 0, 0.

@a1exh: I guess this is a bug, that was not reported before. Because in the original you can't even see it. Map 362 has 8 monsters but all with spawn location 0,0. So they are not on the map.

I strongly think that they should be on the map so I will place them at locations which seem fitting.

**Comment by a1exh** [comment]
Bug spreadsheet updated. 3Map_data.amb - Map 362 (16A). 

Looking at the technical info here https://github.com/Pyrdacor/Ambermoon/blob/master/FileSpecs/Maps.md

To try and work out what you're going to change. Where is the character "SPAWN" X, Y data stored?

There just doesn't seem to be quite enough information for me to work it out.

The monsters each have a "CharacterReference" but is their initial map X,Y in the "CharacterReference::TileFlags"? (There doesn't seem to be a description of this field.) Or maybe "CharacterReference::EventIndex"?

**Comment by Pyrdacor** [comment]
Is is mentioned in the section "Character movement" below.

https://github.com/Pyrdacor/Ambermoon/blob/master/FileSpecs/Maps.md#character-movement

The character move paths (which include spawn locations) are stored in a separate section after the map events. You can think of it like this:
- If a character uses random movement, one position is given (the spawn location)
- Otherwise there are 288 positions (one for each 5 minute slot of the day)
- Monsters (regardless of the random movement flag) always move randomly and only have one spawn location

**Comment by Pyrdacor** [comment]
In this specific case I changed bytes 0x07AC to 0x07BB. They were all 0. Now they have some locations. I just picked valid positions that might fit but I can't know where the monsters actually should have been placed. The positions I used are: 03 0B 03 04 05 06 0B 03 10 06 14 0B 16 0A 15 04

This means:
3,11
3,4
5,6
11,3
16,6
20,11
22,10
21,4

**Comment by a1exh** [comment]
Did the monsters have extra settings like idon't move until seen?

**Comment by Pyrdacor** [comment]
Unfortunately not. They only have the "random movement" flag. So regardless where they are placed, they will move around.
