### ISSUE TITLE
[Bug report] Cannot start ambermoon.net on M1 mac

### ISSUE THREAD

**Issue by comatory** [Pyrdacor/Ambermoon.net#309]
**Describe the bug**
Upon launching the application, OS informs me that the executable is damaged.

**To Reproduce**
1. Download executable from [here](https://ambermoon-net.pyrdacor.net/download/recent/Ambermoon.net-Mac-ARM.zip)
2. Right click executable and select "open"
3. See error

**Expected behavior**
Launch the game.

**Screenshots**
![Screenshot 2022-06-13 at 14 04 31](https://user-images.githubusercontent.com/5990424/173350041-b2b72b14-b38c-4276-aa86-960f80ecd53b.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey 12.4
 - Browser: Chrome
 - Version: 102

**Additional context**
Nothing to add.

**Comment by Pyrdacor** [comment]
I still try to find the reasons for this but the docu is quite limited. Would be nice if someone who develops dotnet on Mac could help. Of course I will try to make it work by myself as well.

**Comment by a1exh** [comment]
M1 Mac is ARM powered. Do you have to build for M1 or are INTEL binaries supported via translation?

**Comment by comatory** [comment]
I did not perform build, I used prebuilt binaries from Github.

**Comment by Pyrdacor** [comment]
I added a build for ARM. It uses the runtime identifier osx-arm64 for compilation/publishing. There is a specific download for it on the main site (readme).

**Comment by Pyrdacor** [comment]
https://docs.microsoft.com/en-us/dotnet/core/rid-catalog

**Comment by comatory** [comment]
ARM macs should still run unsigned apps, maybe it’s some kind of dotnet limitation?

I haven’t tried downloading Intel version, it might run under emulation on M1.

**Comment by Pyrdacor** [comment]
I tried both versions on a Macbook Air now without luck. I know it should work but it doesn't. It keeps saying that the app is damaged and I can't add an exception. Moreover the option to allow apps from everywhere isn't longer available.

On the web I only find examples with compiling it on Mac.

As I build with appveyor it might be possible that their dotnet runtime for building is too old to produce valid ARM executables. But this is only guessing.

**Comment by Pyrdacor** [comment]
I have used another setup for appveyor but my hopes are not high that it changes anything. Anyway can anyone test if 1.6.7 works on M1?

**Comment by comatory** [comment]
On Tue Jun 14, 2022 at 10:38 AM CEST, Pyrdacor wrote:
> I have used another setup for appveyor but my hopes are not high that it changes anything. Anyway can anyone test if 1.6.7 works on M1?

I just tried downloading 1.6.7 (using link from README) and it's the same
story. (M1 Pro)

**Comment by Pyrdacor** [comment]
I most likely found the reason and it took me many frustrating hours. I even opened issues on the official dotnet runtime.

If someone wants to know: new macs (especially the ARM processor ones) need apps to be signed. Dotnet does this automatically when publishing to macOS.

But I do a thing which many apps did back then. I appended custom data to the app. To be precise the whole compressed game data of Ambermoon for all builtin versions. You never wondered why it is only a single exe and no assets? ;) Well now you know.

The problem is that the code signing tool of the macOS has a weird restriction. The Mach-O format which is used has to end with a specific segment. And as I append data, this is no longer true. Unfortunately the error messages were useless here. I found it by heavy testing and luck.

I also wonder why it worked for the Intel version but I don't care any longer.

As Mac bundles everything in a folder anyway and only show that as a single exe, I decided to put the custom data as its own file next to the exe on Mac. So I can sign it. Last tests are running. I hope it works.
