### ISSUE TITLE
[Bug report] Render crash

### ISSUE THREAD

**Issue by Kolump** [Pyrdacor/Ambermoon.net#339]
**Describe the bug**
Hi. Random time bug on pc win 7. Game version Ambermoon.NET (64bit) v1.7.1 english.
Sometime crash on start, sometime can play 5-10 min.

**Screenshots**
![ambermoon error](https://user-images.githubusercontent.com/119890461/206819305-c6915cf3-b8e8-4146-9f65-e2620c90ad1e.jpg)

**Comment by Pyrdacor** [comment]
Looks very much like a OpenGL driver issue. So maybe a video driver update might help.

**Comment by Kolump** [comment]
Hi and thanks for answer.
Unfortunately my computer is very old Duo CPU E8500 and GPU AMD Radeon HD 5700 and use last supported working drivers.
I play many other game and use programs and no have trouble with them.
Maybe is too old to play this game i check and support OpenGL 4.5.
I check new game version 1.8.2 and still same error but i can play much longer.

**Comment by Pyrdacor** [comment]
The problem is that an AccessViolationException (like in your case) is something which is normally produced by hardware or driver issues and it is really hard to react to it in software like Ambermoon.net. Either some memory is broken or a driver is faulty. As this only happens sometimes, it looks very much like corrupted RAM. The stack trace shows that it happens during drawing (where OpenGL draw calls are made) so it is most likely related to the GPU.

I am not sure if I can help you here as the game doesn't do anything fancy there.
