### ISSUE TITLE
[Bug report] Spaceship is completely resetted after first flight

### ISSUE THREAD

**Issue by krater** [Pyrdacor/Ambermoon.net#340]
**Describe the bug**
Maybee this could be a bug in Ambermoon, not in Ambermon.net.
Observed on Ambermoon.net V1.7.1, Ambermoon Advanced 0.01 German on Windows 7.

Space ship's card is resetted after first flight.

**To Reproduce**
1. Go to the spaceship
2. Explore complete card, find skeleton with key, message and amber
3. Take all this with you
4. Use 'grüner Navstein' to flight to the moon
5. Explore card of spaceship again and find again skeleton with key, message and amber

**Expected behavior**
Card is as it was before when you land on the moon.

**Comment by Pyrdacor** [comment]
Beside the chest this is not possible to fix. Technically there are 3 spaceship maps which look identical but have different names and events. One on Lyramion and one on each moon. When you travel to the moons you spawn on a different spaceship map which isn't explored on first visit. I could make it so that the other two spaceships are fully explored but then others might complain as they didn't explore the spaceship completely. But I guess it would still be a better choice.

For the chest: this can be fixed and should work so I will take care of it.

**Comment by krater** [comment]
Another idea would be, that you remove the objects on the skeleton on both moons. You can only get the stone to fly to the moon when you take the key from the skeleton. The amber and the letter from kire are as I know no important things that you need on a moon. So it would be no problem when you can get they only on Lyramion.

**Comment by Pyrdacor** [comment]
Yeah would be possible but it really isn't much of a problem to make it work as it is regarding the chest.

**Comment by Pyrdacor** [comment]
Should work in 1.8.2
