### ISSUE TITLE
Crash on 2D Map

### ISSUE THREAD

**Issue by Thallyrion** [Pyrdacor/Ambermoon.net#36]
I get this crash alway at a very specific place.

See Screenshot - It crashes if i move to the yellow circle.

![2D map crash](https://user-images.githubusercontent.com/69513157/92930087-e3caed00-f441-11ea-96c7-9ad764faea21.png)

Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Ambermoon.Game.ShowTextPopup(PopupTextEvent popupTextEvent, Action`1 responseHandler)
   at Ambermoon.MapExtensions.ExecuteEvent(Map map, Game game, IRenderPlayer player, MapEventTrigger trigger, UInt32 x, UInt32 y, IMapManager mapManager, UInt32 ticks, MapEvent mapEvent, Boolean& lastEventStatus)
   at Ambermoon.MapExtensions.TriggerEventChain(Map map, Game game, IRenderPlayer player, MapEventTrigger trigger, UInt32 x, UInt32 y, IMapManager mapManager, UInt32 ticks, MapEvent firstMapEvent)
   at Ambermoon.MapExtensions.TriggerEvents(Map map, Game game, IRenderPlayer player, MapEventTrigger trigger, UInt32 x, UInt32 y, IMapManager mapManager, UInt32 ticks)
   at Ambermoon.Render.RenderMap2D.TriggerEvents(IRenderPlayer player, MapEventTrigger trigger, UInt32 x, UInt32 y, IMapManager mapManager, UInt32 ticks)
   at Ambermoon.Render.Player2D.Move(Int32 x, Int32 y, UInt32 ticks, Nullable`1 prevDirection, Boolean updateDirectionIfNotMoving)
   at Ambermoon.Game.Move2D(Int32 x, Int32 y)
   at Ambermoon.Game.Move(CursorType cursorType)
   at Ambermoon.Game.HandleClickMovement()
   at Ambermoon.Game.OnMouseDown(Position position, MouseButtons buttons)
   at Ambermoon.GameWindow.Mouse_MouseDown(IMouse mouse, MouseButton button)
   at Silk.NET.Input.Desktop.GlfwMouse.HandleMouseDown(IMouse mouse, MouseButton button)
   at Silk.NET.Input.Desktop.GlfwMouse.<Subscribe>b__62_2(WindowHandle* _, MouseButton btn, InputAction action, KeyModifiers mods)
   at Silk.NET.Input.Desktop.GlfwEvents.<.ctor>b__0_2(WindowHandle* a, MouseButton b, InputAction c, KeyModifiers d)
   at Silk.NET.GLFW.XEEB4BF50.Glfw.PollEvents()
   at Silk.NET.Windowing.Desktop.GlfwWindow.DoEvents()
   at Silk.NET.Windowing.Common.WindowExtensions.<>c__DisplayClass2_0.<Run>b__0()
   at Silk.NET.Windowing.Desktop.GlfwWindow.Run(Action onFrame)
   at Silk.NET.Windowing.Common.WindowExtensions.Run(IView view)
   at Ambermoon.GameWindow.Run(Configuration configuration)
   at Ambermoon.Program.Main()

**Comment by Pyrdacor** [comment]
You're a machine on finding crashes. 😁

World maps don't store a map name which is usually the first map text entry. But I guess the logic is still that text index 0 refers to the map name and index 1 is the first real map text. Without testing it I guess that the world map tries to use text index 1 but there is only index 0 as there is no map name. The solution would be to decrease the index by 1 on word maps. I won't have much time this weekend but maybe @Metibor has time to fix it.

Otherwise I will fix it next week.

Thanks for your excessive testing. It is very helpful. 😊

**Comment by Metibor** [comment]
I had a look at it and the full solution is a little bit more complicated.
The text index itself is fine. 

You can see that, if you walk to the sign at the bridge:
![grafik](https://user-images.githubusercontent.com/12674912/92992157-272c6680-f4e9-11ea-9dfc-c856a143644b.png)

Or further north to the desert:
![grafik](https://user-images.githubusercontent.com/12674912/92992291-36f87a80-f4ea-11ea-856c-c31456f13629.png)

The problem here is, that the PopupTextEvent is at the border of the world map IDs 140/141/156/157.

Each world map id has a different amount of map texts
140: 0 map texts
141: 3 map texts
156: 1 map texts
157: 2 map texts

It seems that the player position vs. map id is a couple of steps off, so that the wrong list of texts for the PopupTextEvent is used.

For example here the event is on map id 157 and the text id is 1 (which is the 2nd text entry) but the list from 156 is used, which only has 1 entry with id 0.
Thats why it crashes.

So first, we need to fix the wrong offset, which should not be too complicated.
But then we still have a problem, because in the original, an event is not exclusively triggered from the player position, but also from the cursor position.

Screenshot from the original:
![grafik](https://user-images.githubusercontent.com/12674912/92992476-855a4900-f4eb-11ea-907a-58bbad064850.png)

A solution would be, to store the map id of the trigger with the event and get the texts for that map id, if the event is triggered.

**Comment by Pyrdacor** [comment]
Ok thanks for the research. I can look into it on monday. I have to look into map event triggering anyway.

**Comment by Metibor** [comment]
I have a bit more research, which could be useful.

If you put this line 
```csharp
Console.WriteLine($"M:{map.Index:000} pX:{Position.X:00} pY:{Position.Y:00} dX:{scrollX:+#;-#;+0} dY:{scrollY:+#;-#;+0} nX:{newX:00} nY:{newY:00}");
```
after `Map.Scroll(scrollX, scrollY);` in Player2D and walk around you will see, that something very fishy is going on where the maps connect.

Example output from walking right (dX:+1) and left (dX:-1) over a map connection:
```
M:156 pX:48 pY:19 dX:+1 dY:+0 nX:49 nY:19
M:156 pX:49 pY:19 dX:+1 dY:+0 nX:50 nY:19
M:156 pX:50 pY:19 dX:+1 dY:+0 nX:51 nY:19 => Should be M:157 pX:00 pY:19 dX:+1 dY:+0 nX:01 nY:19
M:156 pX:51 pY:19 dX:+1 dY:+0 nX:52 nY:19 => Should be M:157 pX:01 pY:19 dX:+1 dY:+0 nX:02 nY:19
M:156 pX:52 pY:19 dX:+1 dY:+0 nX:53 nY:19 => Should be M:157 pX:02 pY:19 dX:+1 dY:+0 nX:03 nY:19
M:156 pX:53 pY:19 dX:+1 dY:+0 nX:54 nY:19 => Should be M:157 pX:03 pY:19 dX:+1 dY:+0 nX:04 nY:19
M:156 pX:54 pY:19 dX:+1 dY:+0 nX:55 nY:19 => Should be M:157 pX:04 pY:19 dX:+1 dY:+0 nX:05 nY:19
M:157 pX:05 pY:19 dX:+1 dY:+0 nX:06 nY:19
M:157 pX:06 pY:19 dX:-1 dY:+0 nX:05 nY:19
M:157 pX:05 pY:19 dX:-1 dY:+0 nX:04 nY:19
M:156 pX:54 pY:19 dX:-1 dY:+0 nX:53 nY:19 => Should be M:157 pX:04 pY:19 dX:-1 dY:+0 nX:03 nY:19
M:156 pX:53 pY:19 dX:+1 dY:+0 nX:54 nY:19 => Should be M:157 pX:03 pY:19 dX:+1 dY:+0 nX:04 nY:19
M:156 pX:54 pY:19 dX:+1 dY:+0 nX:55 nY:19 => Should be M:157 pX:04 pY:19 dX:+1 dY:+0 nX:05 nY:19
M:157 pX:05 pY:19 dX:-1 dY:+0 nX:04 nY:19
M:156 pX:54 pY:19 dX:-1 dY:+0 nX:53 nY:19 => Should be M:157 pX:04 pY:19 dX:-1 dY:+0 nX:03 nY:19
M:156 pX:53 pY:19 dX:-1 dY:+0 nX:52 nY:19 => Should be M:157 pX:03 pY:19 dX:-1 dY:+0 nX:02 nY:19
M:156 pX:52 pY:19 dX:-1 dY:+0 nX:51 nY:19 => Should be M:157 pX:02 pY:19 dX:-1 dY:+0 nX:01 nY:19
M:156 pX:51 pY:19 dX:-1 dY:+0 nX:50 nY:19 => Should be M:157 pX:01 pY:19 dX:-1 dY:+0 nX:00 nY:19
M:156 pX:50 pY:19 dX:-1 dY:+0 nX:49 nY:19 => Should be M:157 pX:00 pY:19 dX:-1 dY:+0 nX:49 nY:19
M:156 pX:49 pY:19 dX:-1 dY:+0 nX:48 nY:19
```
Moving in Y direction is similar.

The tile from the original question is on the border of 156/157 and the output from walking up (dY:-1) is:
```
M:156 pX:50 pY:10 dX:+0 dY:-1 nX:50 nY:09 => Should be M:157 pX:00 pY:10 dX:+0 dY:-1 nX:00 nY:09
M:156 pX:50 pY:09 dX:+0 dY:-1 nX:50 nY:08 => Should be M:157 pX:00 pY:09 dX:+0 dY:-1 nX:00 nY:08
M:156 pX:50 pY:08 dX:+0 dY:-1 nX:50 nY:07 => Should be M:157 pX:00 pY:08 dX:+0 dY:-1 nX:00 nY:07
M:156 PopupText: Text 1, Image None, Unknown 3, Unknown1 00 00, Unknown2 00 00 00 00 => Should be M:157 PopupText: Text 1...
```

**Comment by Pyrdacor** [comment]
Ok I fixed it. Some info:

The movement logic was ok. I know it looks odd but the upper left map is always the "true" map for world maps. So a coordinate of x = 54 is fine cause drawing is based on the scroll offset of the upper left map. To access tiles there is already the indexer for RenderMap2D which handles x and y coordinates that are greater than the map width or height and automatically references the correct adjacent map. So this all worked.

The real problem was that the game used the current map for text indices and not the one which was passed by event triggering. For example `Game.ShowTextPopup` just used `Map.Texts` (where `Map` is the base map) instead of the map of the trigger event (which would be the correct one on world maps). I now pass the map from the event triggering to `Game.ShowTextPopup` and all works ok now. :)

**Comment by Pyrdacor** [comment]
Version 1.1.4 is out now. It should fix the issue and brings a lot of cool new stuff like 3D interactions, riddlemouth and riding horses. :)
