### ISSUE TITLE
Grandfathers vine cellar

### ISSUE THREAD

**Issue by Searcher1978** [Pyrdacor/Ambermoon.net#81]
Hi,

I loaded a game save in version 7.0.0 and then went to grandfather's wine cellar.

The riddle mouth is there again, although I had previously opened it with the word wine. In addition, I cannot address the riddle mouth again. So I'm standing in front of the wall and can't get any further. There is no new query of the word. Instead, I am advised not to speak to myself.

So I don't get any further in the basement, thus also not to the lower level.

This bug was actually fixed in the last version 0.6.x.

Thx for testing.

**Comment by Pyrdacor** [comment]
Hi. Can you give me the savegame please? I will then try to fix this.

**Comment by Searcher1978** [comment]
Hope that´s the right.

[german.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6374504/german.zip)

**Comment by Pyrdacor** [comment]
Ok I found the problem. I guess the savegame is a bit older?

## Background

Each savegame stores which events on maps are active or not (for example if the riddlemouth event is available). This is correctly set to "inactive" in your case so that you can't talk to the riddlemouth anymore.

The savegame also stores "map changes" like that the "riddlemouth wall" is removed. These "map changes" were not stored in older game versions. I think I only added it in 0.6.2 or 0.7.0.

So your savegame memorized that the event was already triggered but not that the wall was removed. This should not happen anymore in recent game versions.

If you want I could try to fix your savegame manually. Otherwise we should check if this happens for savegames that were saved with 0.7.0 onwards.

**Comment by Searcher1978** [comment]
Thx, i´ll start a new game. It´s a early savegame.

**Comment by Pyrdacor** [comment]
Great. Would be nice if you can try the exact scenario (riddlemouth, leave cellar, save, load, return to riddlemouth wall).

**Comment by Searcher1978** [comment]
[german.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6379825/german.zip)
Hi, i tested it once again. The same fault. 
1. I speak to riddlemouth -> the way is open
2. I save and close the game
3. I started the game and load the last savegame
4. The riddlemouce is there, but no chance to talk to it.

Hope that´s help? I used a clear new game in 7.0.0

**Comment by Pyrdacor** [comment]
Ok thanks for testing again. I will try to reproduce this tomorrow and hopefully fix it.

**Comment by Pyrdacor** [comment]
I found the problem. Your report + test was very important. ;)

I mentioned to fix it. I will create an intermediate release today or tomorrow so you can test early. Saving bugs are annoying so I think this is necessary. ;)

**Comment by Searcher1978** [comment]
Nice und very good, that you identify the problem. :)

**Comment by Pyrdacor** [comment]
Should be fixed in 0.7.1beta.

**Comment by Searcher1978** [comment]
It´s fixed, i´ve tested it. Thx! 👍

**Comment by Pyrdacor** [comment]
Great. I'll close this then.
