### ISSUE TITLE
[Approach Suggestion] Open Alchemy

### ISSUE THREAD

**Issue by Wickez** [Pyrdacor/Ambermoon.net#85]
Is there any possibility to bundle the OpenAL's dynamic libraries (_OpenAL32.dll_ & _wrap_oal.dll_) needed for the remake together with its executable? Or, maybe, inside the folder with the remake? Many end users would not bother with installing or even checking on the auxiliary software, thus it would be better to think ahead and supply the stuff required already in the standalone package.

Also, there's a newer and still legit version of Open Alchemy of 2.1.0.0 version [here](https://openal.org/pipermail/openal/2018-May/000694.html) (from Creative Labs itself) than the one usually found (v.2.0.7.0).

Finally, there's a GitHub repository related to (updated?) Open Alchemy [here](https://github.com/kcat/openal-soft) that could provide alternative solution(s)?

**Comment by Pyrdacor** [comment]
I use Silk.NET for sound output and since 2.5.0 it provides the native binaries for OpenAL Soft so that they could be included automatically. Unfortunately there was a bug in the 2.5.0 version which I reported and which was already fixed here: https://github.com/dotnet/Silk.NET/pull/517

But Silk.NET only provides new version every month so we have to wait for the July update 2.6.0. Then this will most likely work without the need to install OpenAL.

**Comment by Pyrdacor** [comment]
But even though let this issue open until it is resolved as a reminder and as information for others. ;)

**Comment by a1exh** [comment]
Using release 0.92 I had to download and install OpenAL before I could get sound.

**Comment by Pyrdacor** [comment]
Yeah still waiting for the July update of Silk.NET. The final release will hopefully have this resolved.

**Comment by Pyrdacor** [comment]
0.9.4 should have built-in OpenAL support.
