### ISSUE TITLE
Screen tearing in 3D sections

### ISSUE THREAD

**Issue by a1exh** [Pyrdacor/Ambermoon.net#91]
Right at the start of the game when you visit Spannenberg in the 3D section if you rotate on the spot you get lots of screen tearing as the game engine updates the screen.

I don't know if you have this level of control but can you enable VSYNC and/or double buffering to stop the screen tearing?

**Comment by Wickez** [comment]
Or you can try it yourself for the fullscreen mode in nVidia/AMD/Intel control panel? Create a profile for _Ambermoon.NET.exe_ and enable the vertical sync for it, bro?

**Comment by a1exh** [comment]
Yes. Using the Nvidia control panel, creating a profile for Ambermoon.Net.exe, overriding the VSYNC setting to always on, solves the screen tearing in the 3D sections. (At least in full screen mode)

**Comment by Pyrdacor** [comment]
I could activate it in code as well but there seems to be an issue in Silk.NET which slows down the mouse movement if it is active and I don't have the time to fix it myself. Even bugfixing Ambermoon is really much work lately and I am at my limits since weeks now.

**Comment by Pyrdacor** [comment]
Next release will have built-in VSync and improved render performance as well. :)

**Comment by Wickez** [comment]
That's terrific!

However, if this option is going to be found inside the game settings menu, and not in the .INI, then please mark that's for the fullscreen only (because it will be enabled by default only for the fullscreen mode, correct?).

Otherwise, you're going to have reports that users still experience tearing in the windowed mode or that the vertical sync option doesn't work at all (when they are in the windowed mode).

**Comment by Pyrdacor** [comment]
This won't be an optional feature. It's always active in window and fullscreen.

**Comment by Pyrdacor** [comment]
Should be resolved in 0.9.4.
