### ISSUE TITLE
Mouse movement

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#92]
I like to move my character keeping the mouse left button pressed, but it's a bit hard because if the cursor touches the character sprite, it changes to the wait mode and you have to release and press the left button again.

Would it be possible to avoid this?

I guess the original had the same problem but I can't remember because I finished more than 20 years ago with the DosFellow emu :)

**Comment by a1exh** [comment]
I seem to remember the original was a little easier to control in 2D than v0.9.3. From memory speed of your character was slightly slower and the I thought that the distance the mouse cursor was from the main sprite affected the speed of movement (further from sprite = faster, closer = slower) but I've played Albion since then perhaps this was a refinement they added after Ambermoon. I'll test against the original using WinUAE soon.

**Comment by Pyrdacor** [comment]
I don't think the move speed changes with distance of cursor. But there was a bug that made the Zzzz cursor area too big. Also see #98. I improved this in the test release which you can try here: https://github.com/Pyrdacor/Ambermoon.net/releases/tag/TestRelease

**Comment by Uukrull** [comment]
Thanks for the fix. I compiled it with an even more reduced radius and, so far, so good :)
